web_server:
  port: 80
  version: 3
  local: true  

wifi:
  enable_on_boot: false
  ap:
    ap_timeout: 0s

#G41=Button
binary_sensor:
  - platform: gpio
    name: Buttonw
    id: g41button
    pin:
      number: GPIO41
      inverted: true
      mode:
        input: true
        pullup: true
    internal: true
    # Toggle the switch when the pushbutton is pressed
    on_press:
      - if:
          condition: wifi.enabled
          then:
            - wifi.disable:
            - logger.log: WiFi is disabled!
          else:
            - wifi.enable:
            - delay: 2s  # Wait for Wi-Fi to enable
            - lambda: |-
                WiFi.softAP("Brink flair 400", "brink400");
                ESP_LOGI("wifi", "WiFi AP SSID set to 'Brink flair 400' with password 'brink400'");
