substitutions:
  name: brink
  friendly_name: Brink
  device_description: "Esphome component for Brink Flair with modbus"
  timezone: "Europe/Amsterdam"
###  Settings Brink Flair (no need to change normally)
###  menu 14-Communication: TypeBus=Modbus, Slave modbusaddress=20, Baudrate=19200, Parity=Even
  modbusaddress: "13"

# In order to use other language or a different ESP chip, fix include file name below:
# Currently supported languages are en, nl. 
# ESP32 is a mh-et-live or wemos d32 mini, esp8266 is a wemos d1 mini, esp32s3 is a lilygo ESP32S3-T7
# Be carefull not to upload the wrong code to the wrong chip. This could brick your ESP chip.
# Choose the correct type for your Brink model, so the correct max flow can be setup with a slider.

packages:
  remote_package:
    url: https://github.com/fonske/Brink-flair-modbus
    ref: main
    refresh: 0s
    files: [ esphome/type/brink-400.yaml,
             esphome/labels/.brink-labels-nl.yaml, 
             esphome/.brink.base.yaml, 
             esphome/boards/board-m5stack-atoms3-lite-fz.yaml,
             # Remove if no enviv sensor available
             esphome/sensors/sensor-enviv-i2c-m5stack.yaml,
             esphome/sensors/sensor-brink_co2_1_sensor.yaml,
           ]

web_server:
  version: 3    

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  logs:
    modbus_controller.sensor: WARN
    modbus_controller.output: WARN
    modbus.number: WARN
    esp32.preferences: WARN
    sensor: WARN
    text_sensor: WARN
    dht.sensor: WARN
    switch: WARN
    button: WARN
    number: WARN
    #DEFAULT DEBUG LOGS
    main: WARN
    modbus_controller.select: WARN
    select: WARN
    bmp280.sensor: WARN